name 'stocker'
maintainer 'Jared & Andy'
maintainer_email 'stocker@snailmail'
license 'All Rights Reserved'
description 'Stocker app host setup'
version '0.1.0'
chef_version '>= 16.0'

depends 'app-attributes'
depends 'app-users'
depends 'apt'
depends 'postgresql'
depends 'local'
depends 'chef_rvm'
depends 'nodejs'
depends 'redis'
depends 'nginx'
depends 'openssh'


